### ISSUE TITLE
CUDA 11 and CUB dependency.

### ISSUE THREAD

**Issue by agalup** [GPUPeople/ouroGraph#1]
Hello, I use CUDA 11.0 and during build I have the error:

```
/usr/local/cuda-11.0/bin/../targets/x86_64-linux/include/thrust/system/cuda/config.h:78:2: error: #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
   78 | #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
```

**Comment by delanyinspiron6400** [comment]
Thank you very much for notifying me, that issue should now be fixed. :)

**Comment by agalup** [comment]
Hello, thank you so much for the quick response! Unfortunately, the another issue still occurs. 

```
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu: In function ‘int main(int, char**)’:
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:89:8: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
   89 |   printf("Using: %s with %llu vertices and %llu edges\n", argv[1], csr_graph.rows, csr_graph.nnz);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           ~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            size_t {aka long unsigned int}
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:89:8: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:100:8: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
  100 |    printf("Smallest Adjacency: %u | Largest Adjacency: %u | Average Adjacency: %u\n", min_adjacency_length, max_adjacency_length, csr_graph.row_offsets[csr_graph.rows] / csr_graph.rows);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:182:8: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘std::vector<unsigned int>’ [-Werror=format=]
  182 |     printf("Basic: %u | DP: %u | PreProc: %u | Class: %u\n", bfs_basic, bfs_dynamic_parallelism, bfs_preprocessing, bfs_classification);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:182:8: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘std::vector<unsigned int>’ [-Werror=format=]
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:182:8: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘std::vector<unsigned int>’ [-Werror=format=]
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:182:8: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘std::vector<unsigned int>’ [-Werror=format=]
/home/agnes/github/ouroGraph/ouroboros/include/device/MemoryInitialization.cuh: In instantiation of ‘void Ouroboros<OUROBOROS, OUROBOROSES ...>::initialize(size_t, size_t, size_t) [with OUROBOROS = OuroborosPages<PageQueue, Chunk<8192>, 16, 10>; OUROBOROSES = {}; size_t = long unsigned int]’:
/home/agnes/github/ouroGraph/include/device/Initialization.cuh:204:1:   required from ‘void ouroGraph<VertexDataType, EdgeDataType, MemoryManagerType>::initialize(const CSR<DataType>&) [with DataType = float; VertexDataType = VertexData; EdgeDataType = EdgeData; MemoryManagerType = Ouroboros<OuroborosPages<PageQueue, Chunk<8192>, 16, 10> >]’
/home/agnes/github/ouroGraph/src/algorithms/BFS.cu:117:27:   required from here
/home/agnes/github/ouroGraph/ouroboros/include/device/MemoryInitialization.cuh:138:8: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
  138 |   printf("Heap Size: ~%llu MB\n", size / (1024 * 1024));
      |        ^~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      size_t {aka long unsigned int}
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/bfs.dir/build.make:63: CMakeFiles/bfs.dir/src/algorithms/BFS.cu.o] Error 1
```

**Comment by delanyinspiron6400** [comment]
Two things:

- What compiler are you using? I tested with GCC10 and CUDA 11 and that seems to work fine, but GCC11 seems to have a problem as of now
- Could you for the moment navigate to the top-level file "BaseCMake.cmake" and look for the keyword `-Werror` and replace that by `-Wall`

Please let me know if that helped :)

**Comment by agalup** [comment]
`-Wall` solved problem :) I can build it now.

I am using the following environment:
```
ouroGraph/build$ lsb_release -d
Description:	Ubuntu 20.04.2 LTS
ouroGraph/build$ cmake --version
cmake version 3.19.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
ouroGraph/build$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
ouroGraph/build$ gcc --version
gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by delanyinspiron6400** [comment]
Awesome! Thanks for letting me know 🙂
